#%RAML 1.0
title: Secured By Null

securitySchemes:
  oauth_2_0:
      type: OAuth 2.0
      describedBy:
          headers:
              Authorization: string
          responses:
              401:
                  description: Invalid or expired token.
      settings:
          accessTokenUri: /token
          authorizationGrants: [ client_credentials ]
  oauth_2_0_withscopes:
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization: string
      responses:
        401:
          description: Invalid or expired token.
    settings:
      accessTokenUri: /token
      authorizationGrants: [ client_credentials ]
      scopes: [ add-a, remove-a, add-b, remove-b, read-c ]
  custom_scheme:
    description: |
      A custom security scheme for authenticating requests.
    type: x-custom
    describedBy:
      headers:
        SpecialToken:
          description: |
            Used to send a custom token.
          type: string
      responses:
        401:
          description: |
            Bad token.
        403:

/A:
    get:
    post:
      securedBy: [  ]
    put:
      securedBy: [ null ]
    delete:
      securedBy: [ null, null, null ]

/B:
    get:
      securedBy: [ oauth_2_0 ]
    post:
      securedBy: [ oauth_2_0, null ]
    delete:
      securedBy: [ oauth_2_0_withscopes: { scopes: [ remove-b ] }, null ]

/C:
    get:
      securedBy: [ oauth_2_0_withscopes: { scopes: [ read-c ] }, custom_scheme ]
